### Create user
POST http://localhost:3000/user/create
content-Type: application/json

{
   "firstName": "Naomi",
   "lastName": "Chege",
   "profileImage": "https://th.bing.com/th/id/OIP.ybNUEwKEf7WR8VIllTWk0wHaE7?rs=1&pid=ImgDetMain",
   "email":"naomichege2512@gmail.com",
   "password": "Nakeez2512",
   "role": "admin"
}

### update user
PUT http://localhost:3000/user/update-user/d4bb5d61-42b1-4bd7-9fd5-98bb8d57d7db
content-Type: application/json

{
   "firstName": "Jane",
   "lastName": "Grace",
   "profileImage": "https://th.bing.com/th/id/OIP.ybNUEwKEf7WR8VIllTWk0wHaE7?rs=1&pid=ImgDetMain",
   "email":"janegrace@gmail.com",
   "password": "Jane1234",
   "role": "user"
}

### delete user
DELETE  http://localhost:3000/user/delete/0af2a87e-6c29-4bb5-ae29-142d08122c0b
Content-Type: application/json

### get all users
GET  http://localhost:3000/user/all-users
Content-Type: application/json

### get one users
GET  http://localhost:3000/user/one-user/423752a5-70e2-4f4a-96dd-c2ece1179573
Content-Type: application/json